jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instalação do .NET SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      # Instalar o SonarScanner como uma ferramenta local
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      # Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # Executar análise do SonarCloud
      - name: SonarCloud Scan Begin
        run: dotnet sonarscanner begin /k:"projeto-chave" /o:"organização-sonarcloud" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportPaths="TestResults/coverage.opencover.xml"

      # Executar testes e coletar cobertura
      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory ./TestResults

      # Compilar o projeto
      - name: Build project
        run: dotnet build --no-restore

      # Finalizar análise do SonarCloud
      - name: SonarCloud Scan End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
